- README.md
This PR contains documentation updates only.
> Improved readme with getting started instructions

- README.md
This PR contains documentation updates only.
> Added class name to Readme example

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
- src/main/java/org/openstreetmap/atlas/generator/creator/AtlasCreator.java
- src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java
- src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
- src/test/java/org/openstreetmap/atlas/generator/AtlasGeneratorTest.java
This PR applies changes proposed in https://github.com/osmlab/atlas/pull/90 
**NOTE**
Until that PR is merged and atlas dependency of this project is updated with the latest atlas release, build will fail.
> Apply CountryBoundaryMap updates

- dependencies.gradle
This PR is just to import the latest bug fixes from Atlas.
> Use latest atlas dependency

- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
This PR is to ensure each shard is processed in a separate task.
> Create a new spark task per shard

- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
This adds logger printouts of the duration of most tasks.
> Print most task durations

- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Fixed issue where `pbfSharding` was accidentally getting initialized to the atlas sharding.
> Fixed bug with pbf sharding initialization

- dependencies.gradle
Upgrade to the latest release of Atlas.
> Use latest Atlas release

- README.md
Added a sonar badge link to the README.
> Added a sonar badge to the README

- dependencies.gradle
> Bump to latest atlas

- build.gradle
- gradle/deployment.gradle
- gradle/dropSonatype.sh
- gradle/releaseSonatype.sh
- gradle/uploadAndRelease.sh
- gradle/uploadToNexus.sh
This solves the issue referenced here: https://github.com/travis-ci/travis-ci/issues/9555
N/A
Already tested with [atlas-checks](
https://travis-ci.org/osmlab/atlas-checks/builds/466829203)
N/A
------
> [HACK] Allow travis to upload to Sonatype from GCE using scripts

- dependencies.gradle
Use latest Atlas.
N/A
N/A
N/A
------
> Depend on Atlas 5.3.0

- gradle.properties
Increment version after release.
N/A
N/A
N/A
------
> Increment version after release

- dependencies.gradle
Use latest atlas 5.3.4
Latest API will be available
Using existing unit tests.
N/A
------
> Use latest atlas 5.3.4

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/PbfLocator.java
- src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
Use retries when loading PBF files from a Hadoop `FileSystem`
PBF loading in `AtlasGenerator` will be more robust.
This is tested by the `AtlasGeneratorIntegrationTest`.
`AtlasGeneratorIntegrationTest` passes.
------
> PbfLocator: Protect against file system failures

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java
Incremented to the newest Atlas version and fixed import statements from com.vividsolutions to org.locationtech, due to the new version of JTS used
List potential impact to downstream libraries here (ex. atlas-checks)
Describe unit tests being added with that PR.
------
> Incremented Atlas version and fixed imports

- .travis/sonar.sh
- src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
Make ResourceFileSystem clearable
Unit tests using ResourceFilesystem can now clear it between uses.
Tested by existing unit tests.
N/A
------
> Make ResourceFileSystem clearable

- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
This PR cleans up some logic around dynamically expanding relations, with further updates coming soon to fully move these to parameters and a default resource file. Additionally, AtlasGeneratorHelper has been cleaned up with an unnecessary method removed and logging made consistent. 
Should be none, as data should be the same.
N/A
------
> Dynamically expanding relation slicing update + logging

- dependencies.gradle
Bump atlas dependency.
N/A
N/A
N/A
------
> Bump atlas dependency

- .circleci/config.yml
- README.md
- build.gradle
- config/checkstyle/arrangement.txt
- config/checkstyle/checkstyle.xml
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerationTask.java
- src/main/java/org/openstreetmap/atlas/generator/tools/spark/rdd/ShardedAtlasRDDLoader.java
This is a followup PR to https://github.com/osmlab/atlas/pull/473
Also add circleCI as 2nd build system.
Method and field arrangement will be enforced.
Using checkstyle.
Tests pass
------
> Use ArrangementCheck

- dependencies.gradle
Bump atlas dependency to latest.
Latest atlas features.
N/A
N/A
------
> Update atlas dependency

- dependencies.gradle
Use the latest Atlas release 5.7.3
https://github.com/osmlab/atlas/milestone/75
https://github.com/osmlab/atlas/milestone/76
N/A
N/A
------
> Depend on Atlas 5.7.3

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
- src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
This PR updates the usage of AtlasLoadingOption to reflect the new changes after the recent line slicing refactor.
None, should not change existing behavior.
N/A
N/A
------
> Minor updates after line slicing refactor

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java
- src/test/java/org/openstreetmap/atlas/generator/sharding/AtlasShardingTest.java
Followup of https://github.com/osmlab/atlas/pull/503, which is required for this to build.
Support for GeoHash sharding.
None
Added a new unit test
Tests pass
------
> Support for GeoHash sharding

- dependencies.gradle
Depend on latest Atlas 5.7.7
None
Use existing tests
Use existing tests
------
> Depend on latest Atlas 5.7.7

- .travis/sonar.sh
- build.gradle
- dependencies.gradle
- gradle/quality.gradle
Fix sonar test coverage, similar as what was done in https://github.com/osmlab/atlas/pull/480
Sonar reports accurate again
N/A
N/A
------
> Fix sonar test coverage

- dependencies.gradle
Update to latest atlas.
Latest and greatest features
N/A
N/A
------
> Update atlas dependency to latest

- dependencies.gradle
Use latest Atlas 6.1.2, and bring in the latest updates.
https://github.com/osmlab/atlas/compare/6.1.0...6.1.2
The most important one being: https://github.com/osmlab/atlas/pull/616
Standard unit tests
Pass
------
> Use latest Atlas 6.1.2

- dependencies.gradle
- src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
- src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Really just changes the AtlasLoadingOption API change in Atlas 6.1.7
Limited or none
------
> Minor updates for new atlas

- src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java
- src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
```HadoopAtlasFileCache``` constructor defines a default fetcher function to read the atlas resource from the file system. This PR adds a couple more constructors that accept a custom fetcher and caching strategy for more flexibility.
No impact on existing usage
Existing unit tests should pass
------
> Accept custom atlas fetcher function

- src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalkerTest.java
Fixed errors that were introduced with the bump to atlas 6.2.0.
Fix build
Existing tests.
Tests pass.
------
> Fixed errors associated with atlas bump

- dependencies.gradle
Use latest Atlas 6.2.7
No impact
Use existing tests
Use existing tests
------
> Use latest Atlas 6.2.7

- dependencies.gradle
- src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
- src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
This PR updates the API usage for slicing to respect the new consolidate logic added in https://github.com/osmlab/atlas/pull/754 
Limited, as this won't affect most data. However, it does enable the new consolidation logic, so it's important to be aware of how to configure that for the desired behavior.
Covered by existing tests.
💯 
------
> Enable consolidation logic for slicing

- src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java
Added a by-ID filter for OSM Nodes to the `AtlasMissingShardVerifier`. This will allow the verifier to ignore problematic nodes that builders of atlases may not want to ingest, and therefore reduce false positives in the verifier's output.
There are some arrangement diffs here too, it's been a long time since anyone has checked on this class 😂
Potential for fewer false positives in verifier output.
Tested by running locally
👍
------
> Added an OSM Node filter to AtlasMissingShardVerifier

- dependencies.gradle
Bump atlas to latest version 6.6.1.
New features.
Existing tests.
Tests pass.
------
> Bump atlas to latest

- scripts/DeployAtlasGeneratorAWS/configuration.json
Adding Caribbean region to the configuration. Need to finalize updated boundary file to use in production runs.
> Adding Caribbean region to configuration

- scripts/cloudPBFShardControl/pbfReShard.py
create script for additional sharding if sharding.txt is outdated.
1) search pbf release folder for shards that larger than 5mb(default).
2) create osmium json config file.
3) execute sharding
4) update release folder, update sharding.txt
sharding strategy will be up to date with the latest data size. 
none
> pbf-reshard script
