src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalker.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSCommand.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalkerTest.java
This PR updates `HDFSWalker`'s `debug` to accept `Consumer<String>` rather than `PrintStream`. `Consumer<String>` is more generic and clients can come up with their own way to consume paths. As an example, I change `FileSystemHelper` to log file path as informational message.
=> Make HDFSWalker debug method accept Consumer<String>

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java, src/main/java/org/openstreetmap/atlas/generator/sharding/OverpassClient.java, src/main/java/org/openstreetmap/atlas/generator/sharding/OverpassOsmNode.java, src/main/java/org/openstreetmap/atlas/generator/sharding/OverpassOsmWay.java
`AtlasMissingShardVerifier` takes the list of missing shards generated by `AtlasShardVerifier`, and checks to see if these shards are missing because they are empty, or because they failed to build. It does this by:
* Finding the multi polygon of intersection between a shard and country boundary
* Querying Overpass for all nodes within that bounding box
* Querying Overpass for all ways within that bounding box
* Subtracting nodes that are a part of ways that are not ingested into atlas (coastlines, boundaries, etc) from the set of all nodes within the bounding box
* If any nodes remain within the multipolygon of intersection after filtering, then the shard was not empty and should have been generated
* The verification returns the list of non empty shards from the missing shards list, …
=> Added a verification that missing shards are actually missing

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSFile.java
This PR adds in a feature to delete a file or directory from HDFS. In case of a directory it will delete it recursively if the recursive flag is set otherwise `CoreException` would be thrown.
=> Delete a path from HDFS

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalker.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalkerTest.java
Current implementation of HDFSWalker traverses all the files and directories in the root using breadth first traversal. Limiting this traversal can have an advantage of filtering out unnecessary directory explorations beyond certain depth and gain some performance. This PR addresses the issue and the consumer of this class can limit the file hierarchy exploration beyond certain depth.
=> HDFSWalker should take in max depth for traversal

src/main/java/org/openstreetmap/atlas/generator/tools/spark/input/SparkInput.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/input/SparkInputTest.java
This PR upgrades `SparkInput` to support binary files the same way it supports sequence files.
The only requirement on the underlying file system is to efficiently return the length of a file, as the binary reader cannot infer the length of a file in advance.
See the new test for an example use case.
=> Add support for binaryFile in SparkInput

src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/CountrySpecificAtlasFilePathFilter.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileOutput.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFilePath.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelperTest.java
SparkFileHelper and dependencies is currently found in [atlas-checks](https://github.com/osmlab/atlas-checks/tree/dev/src/main/java/org/openstreetmap/atlas/checks/persistence). It is a set of utilities that simplifies Hadoop FileSystem interactions with atlas files.
Based on that, the right home for these files is within atlas-generator. After this has been merged, I'll propose a corresponding PR in atlas-checks to update the dependency and remove the files.
=> Moving SparkFileHelper and dependencies from atlas-checks to atlas-generator

src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelper.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelperTest.java
SparkFileHelper currently supports a write method that accepts a String.  Most libraries also support accepting a byte array for general use cases - so proposing the same here.  Also added unit tests for both write methods!
=> Add additional write method to SparkFileHelper that accepts a byte array

src/main/java/org/openstreetmap/atlas/generator/AtlasGenerationTask.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorTaskProcessor.java, src/main/java/org/openstreetmap/atlas/generator/PbfLoader.java, src/main/java/org/openstreetmap/atlas/generator/creator/AtlasCreator.java, src/test/java/org/openstreetmap/atlas/generator/AtlasGeneratorTest.java
This PR updates `AtlasGenerator` to generate `Shard` tasks in Spark master rather than doing it through Spark executors. This process doesn't need to be distributed over executors, because all the information needed for this operation is already available in the master and also the object used for this operation `CountryBoundaryMap` instance might not be not small. Passing `CountryBoundaryMap` instance back and forth adds extra cost and slows down the generation process.
- To make things faster, initial parallelization `JavaRDD` and `JavaPairRDD`s are removed and replaced with `generateTasks` method call. This method goes and generates `AtlasGenerationTask`s to be used in the generation process.
- `AtlasGenerationTaskProcessor` is created to generate tasks in parallel.
- Methods …
=> Move country-shard generation to Spark master

src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelper.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelperTest.java
Committing files by copying to target location.
In some environments renaming files may not be supported.
In case files need to be present in a final location but cannot be renamed there, they can be copied with sources deleted after that.
=> commitByCopy

src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java
This PR adds an option to not print some configuration values in the logs when their keys follow a specified pattern.
=> Do not print configuration values in logs unless allowed

build.gradle
This is to include all the compile dependencies into the shaded jar. Up to now, the shaded jar was empty.
=> Include dependencies in shaded jar

src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
All other parameters are Switches. This is to align `useRawAtlas` with the others.
=> Use switch instead of flag for consistency

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
DNM: This depends on an Atlas release with the changes fromthis Atlas [PR](https://github.com/osmlab/atlas/pull/112).
**Changes**:
1. Replacing country code representation from `IsoCountry` to `String`.
2. Updating logging to give more information as to which shard is being processed rather than which atlas file is being processed. This gives a lot more context as to what's going on when looking through the logs.
**Testing**:
1. Tested on a single country, multiple countries, large and small. Same results as in previous runs.
=> Removing IsoCountry from Raw Atlas Generation

build.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
This enhancement allows the driver to pass around the loading configurations, and thus each slave does not have to download the configuration from the same location.
Also the `propertyMap` contains full configuration files as `String`s.
=> Make Spark pass the configuration around from the driver

build.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Two changes here:
- Removing duplicated code and data version fields. See line 183-184 to find where they are kept.
- @lucaspcram and I found it useful to have the full stack trace present in any potential test failure in the `atlas` project. Adding the same here.
=> Cleanup - removing duplicated fields, adding test failure stacktrace

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Very straightforward change - updating `info` logger statements to become `debug` statements to avoid flooding logs for normally occurring states. Updating another logger statement to have capitalization consistency.
=> Logger level cleanup for AtlasGeneratorHelper

.travis.yml, .travis/build.sh, .travis/sonar-gate.sh, .travis/sonar.sh, build.gradle
The sonar command within the build.sh script would have masked build errors within cron jobs. Breaking it out to follow the same pattern as in atlas.
=> Travis build: Break out sonar

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
Added a subclass of `ConcurrentResourceCache` that provides an easy way of caching Hadoop atlas files in the local tmp file system. Additionally, I have bumped the `atlas` dependency up to `5.1.8`.
Testing Approach
------------------
I have included a unit test that demonstrates properly functionality of the cache. Use of this cache will replace multiple instances of duplicate, handcrafted local caching code.
=> Added a HadoopAtlasFileCache

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Spark allows users to define some stage description so those show up in the UI.
None.
This is visual only. No unit test.
Tested on a local spark cluster:
------
=> Add stage names to be visible in AtlasGenerator job UI

src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
NOTE: This is a WIP tool, and this PR represents iteration 1. I just needed to get something basic working to start tackling some other bugs.
The `RawAtlasCreator` is a new iteration of the `AtlasCreator` designed specifically for the raw atlas flow. When provided with the necessary OSM PBFs, it handles all the `DynamicAtlas` expansion underlying the `WaySectionProcessor` by building the necessary sliced atlases on the fly. It then stores them in a user specified location for re-use.
If you choose not to supply specific underlying OSM PBFs, then the build process will skip expansion into those missing shards.
You can also stop the generation process at any step in the raw atlas flow. This idea is encapsulated by the `RawAtlasFlavor` enum.
Ideas for future refactoring:
1. Allow for a more …
=> Added a RawAtlasCreator command

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
This PR replaces the custom caching code for atlas files with HadoopAtlasFileCache. 
In theory, nothing-- the existing code used the same approach to caching that the HadoopAtlasFileCache implementation does. Given that the implementations are slightly different, it is always possible that some performance changes could occur, but none were apparent during sanity tests.
There does not seem to be a very good way to unit test this functionality; I am open to suggestions.
All existing test pass.
------
=> Switched caching to use HadoopAtlasFileCache instead of custom code

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Protect AtlasGenerator from failing statistics. This is related to an error fixed here: https://github.com/osmlab/atlas/pull/243
Statistics failures will be logged and not fail the job.
TBD
TBD
------
=> Protect AtlasGenerator from failing statistics

.travis.yml
This fixes https://github.com/osmlab/atlas/issues/242 for the atlas-generator project. (Similar to https://github.com/osmlab/atlas/pull/245)
Use sudo=false and dist=trusty in builds. That solves the issue as per https://github.com/travis-ci/travis-ci/issues/9555#issuecomment-413187047
N/A
N/A
------
=> Travis - Use trusty and sudo false

src/integrationTest/java/org/openstreetmap/atlas/generator/world/WorldAtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Added a default boundary map to `WorldAtlasGenerator`, and changed the required flag to optional for the country boundary map parameter. This allows `WorldAtlasGenerator` to be used to create boundary maps from pbf.
This PR also adds the ability to set custom node, relation, and way filters in `WorldAtlasGenerator`, which was also necessary for border file generation.
The default country boundary map provided is set to the width of the world, and a fake country "AAA". Therefore a country boundary map parameter should still be passed in most use cases.
N/A
Tested default boundary map as a part of country boundary map generation.
------
=> Added a default boundary map and configuration options to WorldAtlasGenerator

src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Leverage Spark Broadcast variables for all immutable content that's re-used across stages. See more information [here](http://spark.apache.org/docs/latest/rdd-programming-guide.html#broadcast-variables).
Minor speed up in Atlas-Generator Spark job.
All existing unit tests pass. This change is only testable in a Spark context, which it passed.
Ran a Spark Job that successfully worked at scale with and without the changes. 
------
=> Using Spark Broadcast variables

config/checkstyle/checkstyle.xml, dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/SeekableResourceStream.java, src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java, src/main/resources/log4j.properties, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
This PR removes references to the older Atlas generation straight from PBF. It now defaults to the RawAtlas, and the option to roll back to the older one disappears.
Also:
- Create `AtlasGeneratorParameters` to reduce complexity. This one does just Switch definition and configuration building.
- Enable Atlas scheme (the configurable file path with which Atlas files are saved) which did not work with RawAtlas. It did only work with an empty scheme.
- Depend on Atlas 5.2.3, to benefit from the latest caching improvements: https://github.com/osmlab/atlas/pull/258
Non Raw atlas builds will be impossible.
- Used existing tests
- Fixed AtlasGeneratorIntegrationTest to use the raw atlas folder scheme
- Updated HadoopAtlasFileCache to be aware of the atlas folder scheme
DNM until large scale test …
=> DNM: AtlasGenerator cleanup and fix AtlasScheme being dropped

src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
The `HadoopAtlasFileCache` now better handles the case when the requested `Resource` does not exist - returning an empty `Optional` instead of an invalid "timebomb" `Resource` object. Additionally, users can now specify cache namespaces to create logically distinct caches.
```java
HadoopAtlasFileCache cache1 = new HadoopAtlasFileCache(parentPath, "namespace1", config);
HadoopAtlasFileCache cache2 = new HadoopAtlasFileCache(parentPath, "namespace2", config);
HadoopAtlasFileCache anotherCache2 = new HadoopAtlasFileCache(parentPath, "namespace2", config);
// cache1 and cache2 do NOT share their underlying contents
// cache2 and anotherCache2 do share their underlying contents
```
Users of `HadoopAtlasFileCache` will need to be vigilant when unwrapping the returned `Optional`. They will need …
=> Updates to HadoopAtlasFileCache

src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
This fix allows the Hadoop libraries to find the correct file system implementation.
N/A
Tested locally by building a fat jar and running the class from the command line.
Previously, running this command failed. Now it succeeds.
------
=> Fix default hadoop configuration in WorldAtlasGenerator

src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Adding the ability to specify an edge configuration file when using the `WorldAtlasGenerator`. Also, removing the raw atlas flag, since it was not used and the pbf ingest process already  relies on it by default.
Any users can now pass in a configuration file to specify what becomes an edge when using this generator.
N/A
Integration test passes.
------
=> Adding WorldAtlasGenerator edge configuration

src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java
This PR adds a setter for the `JavaSparkContext` within `SparkJob`. This will allow a spark job to instantiate a spark context, and then pass that context to smaller jobs that comprise the larger one.
Will have no downstream impact.
N/A
N/A
------
=> Added setter for Spark Context in SparkJob

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/AtlasLocator.java, src/main/java/org/openstreetmap/atlas/generator/PbfLocator.java, src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java, src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractMultipleAtlasBasedOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/persistence/scheme/SlippyTilePersistenceScheme.java, src/main/java/org/openstreetmap/atlas/generator/persistence/scheme/SlippyTilePersistenceSchemeType.java, src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelper.java, src/test/java/org/openstreetmap/atlas/generator/PbfLocatorTest.java, src/test/java/org/openstreetmap/atlas/generator/persistence/scheme/SlippyTilePersistenceSchemeTest.java, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelperTest.java
~DNM: doing some last minute testing. Hold merge until ready.~
Ready for merge.
Refactored the `SlippyTilePersistenceScheme` to disallow unsanitized user schemes. Additionally, all hardcoded path construction code (i.e. `foo + "/" + bar`) has been removed.
Potential downstream impact. `SlippyTilePersistenceScheme` still recognizes parameters in formats like `zz/xx/yy`, but now it will throw errors if the format does not match a predefined scheme in `SlippyTilePersistenceSchemeType`. If downstream code is using an unrecognized scheme string, it will either need to be added as a new type in `SlippyTilePersistenceSchemeType`, or the downstream code must update.
New unit tests added (see diff), and old unit/integration tests pass.
All tests pass. Additionally, I built some atlas files locally …
=> Refactored SlippyTilePersistenceScheme and other path code

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractMultipleAtlasBasedOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/persistence/LineDelimitedGeojsonOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleLineDelimitedGeojsonOutputFormat.java
Add an option to save Atlas shards as line delimited geojson files.
No impact, just new option available.
Ran job in integration test
Integration test passes.
------
=> Save Atlas as line delimited geojson

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
This PR adds compatibility for the new slicing logic in osmlab/atlas#341. Primarily, the changes rework AtlasGenerator and AtlasGeneratorHelper to separate point-and-line slicing from relation slicing, and add in a DynamicAtlas fetcher that will fetch the line sliced Atlases during relation slicing.
Additional work has been done to update RawAtlasCreator to enable these new slicing changes as well.
Output Atlas files should simply incorporate the changes from the new slicing logic, but it is worth pointing out that several subdirectories have been added or renamed as part of the rework. 
None
------
=> Dynamic slicing

README.md, build.gradle, config/checkstyle/checkstyle.xml, dependencies.gradle, gradle/execution.gradle, gradle/quality.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
Upgrade gradle to 5.
Related necessary updates:
- Gradle wrapper 5.2.1
- Checkstyle 8.18
- Some checks that were already enabled started working, so fixed the related issues.
- Spotless 3.18.0
- No need to remove removeUnusedImports anymore
- `importOrder([ x, y, z])` becomes `importOrder x, y, z`
- gradle run updates
- The double left `<<` is now invalid. Replaced by `doLast{...}`
- `runGenerator.execute()` is invalid. Replaced by `run.finalizedBy(runGenerator)` at the end.
- Added maven central badge
The impact should be confined to this repository.
Use existing tests.
Use existing tests.
------
=> Upgrade to Gradle 5

dependencies.gradle, src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
This PR reworks AtlasGenerator to use a new enum, AtlasGeneratorJobGroup, to manage the Strings and output formats associated with each stage of the Spark job for AtlasGenerator. Additionally, the performance of relation slicing is improved-- now, the lineSlicedSubAtlas creation will use a more aggressive filter that keeps only lines and relations tagged with appropriate tags, and uses SilkCut to ensure their underlying Points are also included. This dramatically reduces the amount of geometry loaded by the dynamic exploration during relation slicing. 
None, as all data should be the same.
None, as all data should be the same.
------
=> Streamline AtlasGenerator and improve slicing performance

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/ResourceFileSystemTest.java
Allow for saving a test `ResourceFileSystem` to disk.
New feature.
Added one unit test.
Test passes
------
=> Dump ResourceFileSystem to disk

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java
Added an optional switch to the `AtlasMissingShardVerifier` that takes a configurable way filter. If no filter is provided, it will default to the osm-pbf-way filter which is a resource in the atlas project.
Allows verification to match the atlas generation configuration for way ingest.
Tested locally passing a configuration, and also using the default value.
Switch works as intended.
------
=> Update Missing Shard Verifier to use configurable way filter

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
Adds an option to create a separate, filtered output after final Atlas generation is finished. If no filter is provided, the filtering step will not be run. If a filter is provided, it should be in the form of a JSON taggable filter file; after Atlas generation, all generated Atlas files will be written to the 'filteredOutput' subdirectory using a SOFT_CUT subatlas call. 
None, as there are no changes if the filter is not provided.
Describe unit tests being added with that PR.
------
=> Added in configuration option for filtered output

dependencies.gradle, src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java, src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
This PR fixes compile issues with a recent change to the constructor of RawAtlasCountrySlicer. The constructor now takes a single AtlasLoadingOption, and uses the CountryBoundaryMap, Countries, and EdgeFilter from it to set up country slicing.
Additionally, way-sectioning now creates a separate folder for edge-only Atlases, in order to speed up way section performance during dynamic Atlas expansion during way-sectioning.
No data changes, so minimal impact.
Describe unit tests being added with that PR.
------
=> Fixed RawAtlasCountrySlicer constructors, added edge-only subatlas caching

.travis/build.sh
Integration tests were only being run on release builds, not PRs. This meant that a PR with a breaking integration test change would be merged with a build passing marker.
Will run integration tests for all builds, not just release builds.
This PR build passing
We will see!
------
=> Run integration tests for PR builds as well

src/integrationTest/java/org/openstreetmap/atlas/generator/tools/spark/SparkJobIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java
Simplification and cleanup of the SparkJob class. The StartedFolder is removed and logging is simplified. Also removed a bunch of sonar errors.
Some downstream jobs relying on some switches might have to be updated.
Added one simple integration test.
Tests pass.
------
=> Simplification and cleanup of SparkJob

src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Fixes a major issue where the wrong RDD pair is used for the mapping function for relation slicing. The proper RDD pair is the lineSlicedRDD, not the already uncached countryRawAtlasRDD
List potential impact to downstream libraries here (ex. atlas-checks)
Describe unit tests being added with that PR.
------
=> Fixed wrong RDD pair map for relation slicing

build.gradle, dependencies.gradle, src/integrationTest/java/org/openstreetmap/atlas/generator/tools/spark/rdd/ShardedAtlasRDDLoaderTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractFileOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/input/SparkInput.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/sharded/ShardedSparkJob.java, src/test/java/org/openstreetmap/atlas/generator/tools/spark/input/SparkInputTest.java
This PR enables Spark 2.4 (previous was 1.6). Most code is unchanged, though two tests have been disabled as they have compatibility issues with Spark 2.4 and JDK 11. Otherwise, the most exciting change here is that all RDD.unpersist() calls are now wrapped in try/catch blocks due to occasional harmless timeouts. 
None, ideally.
N/A
------
=> Enabled support for spark 2.4

src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
This PR allows for overriding the slicing configuration used to decide which relations will be dynamically expanded on during relation expansion. Default is the default from AtlasLoadingOption.
This PR requires [this PR from Atlas](https://github.com/osmlab/atlas/pull/438) to be merged and released before it will build properly.
N/A
N/A
N/A
------
=> Added in support for slicing configuration override

src/main/java/org/openstreetmap/atlas/generator/sharding/PbfVerifier.java, src/test/java/org/openstreetmap/atlas/generator/sharding/PbfVerifierTest.java
Added a zero file size check to the `PbfVerifier`. Since PBF's that contain no data still contain metadata, any 0 byte PBF is a result of a write failure in the PBF generation process. Therefore, finding a size 0 PBF will cause the verifier to fail.
`PbfVerifier` will fail on empty pbf files.
Updated the `PbfVerifierTest` to accommodate the changes. Tested 0 size pbf detection locally.
Tests ran successfully.
------
=> Check for corrupt PBFs

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/converters/ConfigurationConverter.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/persistence/PersistenceTools.java, src/test/java/org/openstreetmap/atlas/generator/AtlasGeneratorTest.java
This allows the `AtlasGenerator` job to save the Sharding tree and Boundary file to the output folder. If present in the input PBF folder, it also uses those sharding and boundary files in priority, rather than the ones supplied in the parameters.
This should be transparent to existing toolchains, as the existing parameters are still valid.
Updated `AtlasGeneratorIntegrationTest`
Tests pass. Also the `./gradlew run` command still works as expected.
------
=> Tooling to save Sharding and Boundaries to output folder

config/checkstyle/checkstyle.xml, src/integrationTest/java/org/openstreetmap/atlas/generator/tools/spark/rdd/SparkRDDTestBase.java
The `RequireThis` plugin in Checkstyle was updated after `6.17`, and this update was missed.
Adding
```xml
<property name="validateOnlyOverlapping" value="false"/>
``` 
enforces the same behavior as before.
Thanks @Huyuntj for finding out!
- Fixes all the violations that sneaked in in the mean time.
- Updates code ordering when it was not alphabetical
No impact, code style and readability only.
Use same tests
Tests pass
------
=> Checkstyle RequireThis changed and update was missed

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/converters/ConfigurationConverter.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/persistence/PersistenceTools.java
This fixes the access of boundary files using `PersistenceTools` which was failing to read gzipped files properly.
The copying of resources is unchanged, however the boundary deserialization now works.
Using same unit tests
Same
------
=> Proper centralization of resource accession

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/integrationTest/resources/org/openstreetmap/atlas/generator/nothingFilter.json, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/world/AtlasFilePathFilter.java, src/main/java/org/openstreetmap/atlas/generator/world/WorldMultiAtlasGenerator.java
This PR adds an option to Altas generation for configured filter output. This output is optional, and allows for more complicated predicates to be used in filtering output than the `ConfiguredTaggableFilter`.
Also added in this PR is the `WorldMultiAtlasGenerator`, which is a command that takes an atlas directory and creates a corresponding multi atlas.
Adds an option for configured filtered output to atlas generation.
Tested atlas generation with and without the optional configured filter.
Filtered output was as expected.
------
=> Added configured filter output option to Atlas Generation

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
AtlasFetcher functions' logs for country slicing and way sectioning are missing the country, which makes debugging harder. Here the country is added to the log messages.
Better logs
Use existing tests
Use existing tests
------
=> Print the country in atlas fetcher logs

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
This depends on https://github.com/osmlab/atlas/pull/536
Once an Atlas file is downloaded by `HadoopAtlasFileCache`, make sure it is not corrupt.
This will throw an exception if the file is corrupt and it cannot open it. Since these are files at this point, it will not try to load the whole Atlas, but only the meta-data, which should be pretty lightweight.
Use existing tests
Use existing tests
------
=> Validate downloaded atlas files in HadoopAtlasFileCache

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifier.java
Now that the `Shard#getName` method has been standardized, any code attempting to write a parsable shard string should be using this method.
See: https://github.com/osmlab/atlas/pull/541
Parsing code expecting `toString` to give parsable output may be broken. This fixes that issue.
N/A
N/A
------
=> AtlasShardVerifier now uses getName instead of toString

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/integrationTest/java/org/openstreetmap/atlas/generator/persistence/FeatureChangeOutputFormatIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/persistence/FeatureChangeOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleFeatureChangeOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
Added a new `FeatureChangeOutputFormat` to be able to save RDDs of lists of `FeatureChange`s.
Also:
- Fixed a few sonar errors
- Aggregated the addResource methods to ResourceFileSystem
None
Added one integration test
pass
------
=> Output Format for FeatureChange lists

src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractFileOutputFormat.java
Add a retry when closing the stream in `AbstractFileOutputFormat`. This was one area that was not covered by a retry before and that was a gap.
Safeguard against more types of network failures
Use existing integration tests
Use existing integration tests
------
=> AbstractFileOutputFormat: Retry when closing the stream

src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
During relation slicing, the Atlas being sliced is dynamically expanded upon to complete any multipolygon relations. However, until now, the Atlas fetcher function used for this dynamic expansion has been inefficient-- it defaulted to fetching the Atlas for the initial shard from a HadoopAtlasFileCache. This approach ignores that the RDD value for the relation slicing already has the Atlas data for the initial shard stored, so now the fetcher stores that value and will return it directly instead of attempting to load from the HadoopAtlasFileCache.
Fewer HadoopAtlasFileCache calls, so possibly improved performance, but otherwise no impact.
N/A
N/A
------
=> Reworked atlas fetcher function to improve performance

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java, src/main/java/org/openstreetmap/atlas/generator/persistence/AtlasProtoOutputFormat.java, src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleAtlasFeatureChangeOutput.java
This PR replaces the AtlasDelta step with AtlasDiff, a replacement with similar functionality but based on the `AtlasDiff` class for comparing two Atlases. Passing in output from a previous Atlas generation, AtlasDiff will attempt to compare any newly generated Atlases to ones from the previous output. Brief summary logs for object types and tags will be generated, then a GeoJSON diff for the Atlases will be saved to the output folder.
Depends on https://github.com/osmlab/atlas/pull/579
Minimal, this approach is a more robust AtlasDelta. However, any reliance on AtlasDelta reports will need to be updated, and it's possible that more updates will be needed to augment AtlasDiff as part of supporting anyone making that transition.
N/A
N/A
------
In doubt: [Contributing …
=> Replace AtlasDelta with AtlasDiff based approach

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
When the RDD keys were switched to JSON in #123 country AtlasStatistics were not upgraded by mistake. The integration test did not fail either since the merging of the shard statistics was taking the last shard statistics object available, making it look valid.
This PR fixes that omission and adds steps to the integration test to make sure it does not happen again.
Country Statistics are back to normal numbers.
Updated integration test
pass
------
=> Fix Json key issue with AtlasStatistics

dependencies.gradle, src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifier.java
Depend on latest Atlas 5.9.1
This release contains a breaking change for AtlasResourceLoader
Existing tests
Existing tests
------
=> Depend on latest Atlas 5.9.1

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
When an older Atlas file isn't found, log it as empty instead of throwing CoreException.
None.
N/A
N/A
------
=> Fix CoreException during AtlasDiff

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
`ResourceFileSystem` is used to mock a `Filesystem` for integration tests. The option to copy its contents to disk was erroneously re-gzipping the contents of files ending in `.gz`. This PR fixes that issue!
Better representation of the data when debugging
None, this is for tests.
N/A
------
=> Do not re-gzip when dumping ResourceFileSystem to disk

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java, src/test/java/org/openstreetmap/atlas/generator/sharding/AtlasShardingTest.java
If a `dynamic` resource passed to an `AtlasSharding` constructor did not exist, then a NPE would be thrown. This simple PR updates that to have a better error message.
Better error message.
Added one unit test
Pass
------
=> Prevent NPE in AtlasSharding when resource does not exist

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
The AtlasStatistics portion of AtlasGenerator might not be necessary in all jobs. Here we make it optional with a switch to enable it.
Test jobs will be faster
Updated integration test
Pass
------
=> Make AtlasStatistics optional

src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
We have been seeing a number of cron builds fail in the `HadoopAtlasFileCacheTest`. [See here for example.](https://travis-ci.org/github/osmlab/atlas-generator/builds/630884931)
My hunch is that this is due to JUnit running the tests in `HadoopAtlasFileCacheTest` in parallel, and some of the tests may be stepping on each other's toes (since they are hitting the global filesystem presumably at /tmp).
This PR aims to force JUnit to run the tests sequentially.
Hopefully 🤞we stop seeing cron build failures.
See changes. We updated a unit test.
Test runs OK. We can only become increasingly more confident that the bug has been fixed as we continue to see cron build successes.
------
=> HadoopAtlasFileCache tests now performed sequentially

src/integrationTest/java/org/openstreetmap/atlas/generator/tools/spark/SparkJobIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java
When a `SparkJob` failed and the context was cleared before the "FAILED" file could be written to the output folder, the error displayed would be the writing error instead of the actual cause of the job failure.
This PR fixes that by displaying both.
Easier to troubleshoot
Added one integration test
Pass
------
=> Propagate right error message in SparkJob

src/main/java/org/openstreetmap/atlas/generator/PbfLoader.java
Remove the loading area boundary from the raw atlas metadata tag list. When multiatlasing many shards together, this tag was causing the metadata tag list to bloat to unreasonable levels.
Shard loading area will no longer be a tag present in the raw atlas.
N/A
Tested locally, mutliatlases had their size dramatically reduced.
------
=> Removed loading area boundary from metadata tags

src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractFileOutputFormat.java
When a file system `close()` fails in `AbstractFileOutputFormat`, and the object written is the first one, the error message would print null. This fixes it by setting the temporary objects first before writing them to the file system.
Better logging
Code is already covered by tests
Pass
------
=> Save the lastKey and value first to properly populate exception message

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifier.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/test/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifierTest.java
The AtlasShardVerifier is a command that makes sure that a folder containing Atlas files has all the expected shards. New features are:
- The reference can now be:
- A file containing a list of expected shards
- A path to a directory containing Atlas files
- The directory to check does not have to be on the local file system, it can be on any hadoop `FileSystem`
More use cases supported
- Added one unit test
- Fixed integration test
Pass
------
=> AtlasShardVerifier to work with any FileSystem

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifier.java
This is a followup to #153.
This makes the spark options retrieval in `AtlasShardVerifier`, as well as the path retrieval, a separate method that can be overriden by the user who would want to control the connection options programmatically.
Also the method returns an error code when some shards are missing.
More flexibility
Existing tests
Existing tests
------
=> AtlasShardVerifier: Make the sparkOptions an overridable method

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasShardVerifier.java
In https://github.com/osmlab/atlas-generator/pull/154 a failure condition was added to `AtlasShardVerifier`, which would fail the command if there were any "missing" shards. However, these missing shards are calculated by taking the difference of the expected shards, and the shards that were actually built. This difference is therefore not a set of confirmed missing shards, but instead a list of shards that could potentially missing. This set of shards needs to be fed into an overpass query to see if they are legitimately empty or not. Failing here is premature, and therefore has been removed.
Removes early failure condition.
Existing tests.
Tests pass
------
=> Remove failure condition from AtlasShardVerifier

src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/integrationTest/resources/org/openstreetmap/atlas/generator/highwayFilter.json, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
This PR adds functionality to take in a list of configured output filters and filter names and save each filtered output in a directory under the configuredOutput. 
Increases flexibility. No impact downstream.
Add additional integration testing.
Passed
------
=> Add ability to create multiple filtered atlases with configured output filter

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java, src/main/java/org/openstreetmap/atlas/generator/sharding/OverpassClient.java, src/test/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifierTest.java
Split `AtlasMissingShardVerifier` master query into subqueries, if one query has too much data returned at once. This will allow accurate results on runs with large amounts of data missing.
`AtlasMissingShardVerifier` can now handle runs with more missing data.
Unit test for logic surrounding building the sub queries.
Tests pass.
------
=> Split AtlasMissingShardVerifier query if too much response data

dependencies.gradle, src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java, src/integrationTest/java/org/openstreetmap/atlas/generator/world/WorldAtlasGeneratorIntegrationTest.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java, src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
Now that `ConfiguredFilter` is accepted by `AtlasLoadingOption` (after https://github.com/osmlab/atlas/pull/660 and https://github.com/osmlab/atlas/pull/662) this update makes AtlasGenerator accept `ConfiguredFilter` filters for all non-pbf filtering needs.
Also:
- Remove remnants of `SHOULD_ALWAYS_SLICE_CONFIGURATION` the logic of which had been removed a few versions ago.
More options for configuring the job, including the option to choose geometrical areas where the OSM Ways become `Edge`s for example. It is also backwards compatible, so the previously used `ConfiguredTaggableFilter` filter arrays like [this one](https://github.com/osmlab/atlas/blob/6.2.3/src/main/resources/org/openstreetmap/atlas/geography/atlas/pbf/atlas-edge.json) will still work. For reference [here is the same …
=> AtlasGenerator to use ConfiguredFilter when possible

build.gradle, dependencies.gradle
Now make atlas-generator target Spark 3+
Limited, though support for Spark 3 will now be required.
------
=> Update dependencies to use Spark 3

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/ResourceFileSystemTest.java
ListStatus doesn't handle directories right now, this PR adds support to return directories in cases where the prefix is a partial path.  
If the prefix is something like resource://test/path and the filepath is resource://test/path/to/a/file, a listStatus on resource://test/path will return the full filePath, not the next directory.  With this PR, we will now return resource://test/path/to and mark it as a directory.
There will now be some preliminary support for directory handling in listStatus.  ResourceFileSystem is mainly used in test cases only, so limited impact.
Add a unit test for listStatus in ResourceFileSystemTest
Make sure all other unitTests still work
New unit Tests added!
All other unitTests still pass!
------
In doubt: [Contributing …
=> Add directory support to listStatus

src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java, src/main/java/org/openstreetmap/atlas/generator/PbfLoader.java, src/main/java/org/openstreetmap/atlas/generator/PbfLocator.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemCreator.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/DataLocator.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/input/SparkInput.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/rdd/ShardedAtlasRDDLoader.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/utilities/SparkFileHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSFile.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalker.java, src/test/java/org/openstreetmap/atlas/generator/PbfLocatorTest.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSFileTest.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/HDFSWalkerTest.java
This fixes a resource leak, which will improve resource usage.
Put `org.apache.hadoop.fs.FileSystem` creation into `try-with-resource` blocks. This ensures that the `FileSystem` is properly closed. There are also some fixes for sonar sprinkled in (mostly deduplication of strings).
Major impact: Less resource utilization
No impact: No new exceptions are thrown (those that are thrown through the try-with-resources are caught and handled silently, to avoid breaking downstream users).
N/A
With https://github.com/osmlab/atlas-checks/pull/398, I was able to reduce the memory required to run the test check on NZL from 15 GB to 1GB. It may have been possible to run it with less memory (so < 1GB).
Notes:
* Additional modifications to `atlas-checks` was required in order to run the current `dev` …
=> Spark FileSystems should be closed when no longer needed.

build.gradle, gradle/quality.gradle
This is a followup of https://github.com/osmlab/atlas-generator/pull/174 with respect to the [Atlas Query Language](https://github.com/osmlab/atlas/tree/6.4.0/src/main/groovy/org/openstreetmap/atlas/geography/atlas/dsl#atlas-query-language-aql) linting.
We add a build task which lints the AQL scripts included in the repo. 
None
None
AQL lint task passes!
------
=> AQL Linting

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemCreator.java, src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/persistence/PersistenceTools.java, src/main/java/org/openstreetmap/atlas/generator/tools/spark/sharded/ShardedSparkJob.java, src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
Add Closeable Resources, for use when a Resource depends upon an AutoCloseable resource that must not be closed prior to the user finishing with the resource.
This largely comes down to memory impact. In osmlab/atlas-generator#167, closing resources significantly freed up space and sped up processing. Unfortunately, during testing, a bug where resources were closed prior to reads was missed. This fixes that issue by creating resources that store the closeable resources internally, which can then be closed automatically when finished.
This may have been missed due to specifying a `-sharding` parameter and/or a less congested network.
I've done several runs with an executor on a Raspberry Pi (also running a hadoop server) with two worker nodes on Mac computers.
This depends upon …
=> AutoCloseable: Use autocloseable resources appropriately

scripts/cloudPBFShardControl/pbfShardGenerator.py
This adds retry logic for when one call to osmium fails. We have seem where sometimes osmium can hog memory and run out and if retried it generally works so this will prevent the sharding process from failing just because one call to osmium failed. It allows for 10 retries.
AWS sharding script could take longer if there are some failures but will eventually succeed. 
Manually tested in AWS environment an used random "sudo killall osmium" calls to test that it could deal with failures. 
All good.
=> Add osmium retry logic to AWS sharding script.

src/main/java/org/openstreetmap/atlas/generator/PbfLoader.java
PbfLoader accidentally regenerates raw atlases instead of using the sub atlas optional 💀 
Data quality should be better limited to shard bounds, atlas generation time will drop since we don't do it twice anymore
No unit test since this actually behaved as expected with respect to data generation, it's just doing it twice unnecessarily.
------
=> Fix bug in PbfLoader

.github/workflows/ci.yml, build.gradle
Attempt to fix a build issue with osgeo rejecting log4j1 calls by putting maven central first in the repo list.
May unblock builds
None
None
------
=> Put maven central first

src/main/java/org/openstreetmap/atlas/mutator/AtlasMutatorHelper.java
Very small PR to address an occasional issue where sometimes shard data is improperly calculated due to dynamic atlas expansion. While a fix could hypothetically be made in DynamicAtlas, it actually makes more sense to include here-- the mutator driver itself is responsible for creating an expanded Atlas for a given shard (possibly extensively outside the shard bounds), at which point the "origin" shard is really only known to the mutator driver. Thus, having the mutator driver ensure the final Atlas is both trimmed to shard bounds *and* has the proper metadata is appropriate.
Limited, outside of a piece of metadata being more consistent.
------
=> Override Atlas metadata to guarantee shard name is correct

build.gradle, dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/org/openstreetmap/atlas/generator/tools/spark/persistence/PersistenceTools.java
Move to slf4j logging throughout atlas generator.
I should have used slf4j initially, anyway.
There should be no impact on downstream projects.
See also
* https://github.com/osmlab/atlas-checks/pull/644
* https://github.com/osmlab/atlas/pull/780
=> PersistenceTools: log4j -> slf4j logging

src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java, src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/ResourceFileSystemTest.java
`ResourceFileSystem` now fills in length and block size in the `FileStatus`. This is helpful for integration tests that want to use `sparkContext.sequenceFile` to read an RDD.
`ResourceFileSystem` should now work with `sparkContext.sequenceFile`.
`ResourceFileSystem` unit tests.
👍
------
=> Some tweaks to resource FS so that we can run integration tests with sparkContext.sequenceFile

src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java
`AtlasSharding` was obscuring the exception stack trace in the `dynamic` use case. This update is to have it print the underlying stack trace.
None
None
Tested locally
------
=> Do not obscure exception stack trace in AtlasSharding
